name: deploy-to-aws
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: main
    types: closed
    paths-ignore: '.github/workflows/**'

jobs:
  build-test-upload:
    uses: ./.github/workflows/build-and-test.yml
    with:
      artifact-name: build-files

  deploy:
    needs: build-test-upload
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true

    permissions: # for GitHub OpenID Connect token
      id-token: write
      contents: read

    steps:
      - name: debug
        run: |
          echo event: ${{ github.event_name }}
          echo ref: ${{ github.ref }}

      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-files
          path: build-files

      - name: print current directory
        run: |
          ls
          cd ..
          ls

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ SECRETS.AWS_GITHUB_ROLE }}
          aws-region: us-west-2

      - name: deploy to S3 bucket
        run: aws s3 sync build-files/ s3://portfolijo --delete

      - name: invalidate cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ SECRETS.AWS_CLOUDFRONT_DIST_ID}} --paths "/*"
