name: deploy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: closed

jobs:
  build-and-deploy:
    runs-on: windows-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          
      - name: install dependencies
        run: npm install
        
      - name: run tests
        run: npm run test
        
      - name: build project
        run: npm run build
        
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: deploy to S3 bucket
        run: aws s3 sync ./build/ s3://portfolijo --delete
