name: test-build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened] # synchronize = new commits pushed

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: install node
        uses: actions/setup-node@v3
        # using later versions of node breaks due to react-scripts v5.0.1 incompatible with typescript v5;
        # this specific node/npm version works though
        with:
          node-version: "16.14.2"
          npm: "8.5.0"
          
      - name: install dependencies
        run: npm install
        
      - name: run tests
        run: npm run test
        
      - name: build project
        run: npm run build
