name: test-workflow
on:
  workflow_dispatch:
  push:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Enable debug logging
        run: echo "::debug::Debug logging enabled"

      - name: test secret
        run: echo ${{ secrets.TEST_SECRET }}
